# Generated by Django 5.2.7 on 2025-10-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta_correcta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('alternativa_A', models.CharField(max_length=255)),
                ('alternativa_B', models.CharField(max_length=255)),
                ('alternativa_C', models.CharField(max_length=255)),
                ('alternativa_D', models.CharField(max_length=255)),
                ('dificultad', models.CharField(choices=[('facil', 'facil'), ('medio', 'medio'), ('dificil', 'dificil'), ('experto', 'experto')], db_index=True, max_length=50)),
            ],
        ),
    ]
