# Generated by Django 5.2.7 on 2025-11-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta_correcta', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('alternativa_a', models.CharField(max_length=255)),
                ('alternativa_b', models.CharField(max_length=255)),
                ('alternativa_c', models.CharField(max_length=255)),
                ('alternativa_d', models.CharField(max_length=255)),
                ('dificultad', models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil'), ('Experto', 'Experto')], db_index=True, max_length=50)),
                ('tipo', models.CharField(choices=[('trigonometria', 'trigonometria'), ('álgebra', 'álgebra'), ('estadística', 'estadística')], db_index=True, default='álgebra', max_length=100)),
            ],
        ),
    ]
