# Generated by Django 5.2.7 on 2025-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADAPTACION', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='alternativa_A',
            new_name='alternativa_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='alternativa_B',
            new_name='alternativa_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='alternativa_C',
            new_name='alternativa_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='alternativa_D',
            new_name='alternativa_d',
        ),
        migrations.AlterField(
            model_name='question',
            name='dificultad',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Medio', 'Medio'), ('Dificil', 'Dificil'), ('Experto', 'Experto')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='respuesta_correcta',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1),
        ),
    ]
