# Generated by Django 5.2.7 on 2025-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADAPTACION', '0002_rename_alternativa_a_question_alternativa_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tipo',
            field=models.CharField(choices=[('trigonometria', 'trigonometria'), ('álgebra', 'álgebra'), ('estadística', 'estadística')], db_index=True, default='álgebra', max_length=100),
        ),
    ]
